name: Test
on:
  push:
    branches:
      - '**'

  pull_request:

  schedule:
    - cron: '0 0 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - name: test
        run: |
          go generate
          godev -m 100

      - uses: codecov/codecov-action@v1
        if: ${{ always() }}

  others:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - name: test
        run: go test -v -race -run Test

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
          docker build -t rodorg/rod -f lib/docker/Dockerfile .
          docker build -t test -f lib/docker/test.Dockerfile .
          docker run -v $(pwd):/t -w /t test
